apiVersion:  apps/v1

kind: ReplicaSet

metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    name: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp

    spec:
      containers:
      - name: nginx-container
        image: nginx
  # modify replicas according to your case
  replicas: 3
