apiVersion: v1

kind: Pod
metadata:
  name: myapp-pod
# under labels we can give any key:value pair, it does not provide any suggestion.
  labels:
    name: myapp-pod
    app: myapp
    type: pod
spec:
  containers:
  - name: nginx-image
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: password
        value:  abc
