apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector: # can copy data from pod-definition file in metadata-> labels data section.
  # or can copy from deployment-definition. yml file under template->metadata->labels data
    app: myapp
