apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  # type: LoadBalancer #does't support on VM machien, it's support on gcp
    type: nodePort: 30009 # on VM we have to user nodePort.
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
